[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
flion = { path = "../flion" }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[build-dependencies]
flion-build = { path = "../flion-build" }
