[package]
name = "fluster"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["flutter-embedder"]

[dependencies]
color-eyre = "0.6"
flutter-embedder = { path = "flutter-embedder" }
gl = "0.14"
khronos-egl = { version = "4.1", features = ["static", "no-pkg-config"] }

[dependencies.windows]
version = "0.48"
features = [
    "Foundation_Numerics",
    "Graphics_DirectX",
    "System",
    "UI_Composition",
    "UI_Composition_Desktop",
    "Win32_Foundation",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_DirectComposition",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_System_WinRT",
    "Win32_System_WinRT_Composition",
    "Win32_UI_WindowsAndMessaging",
]

[build-dependencies]
dunce = "1.0"
vcpkg = "0.2"
